 //Completed lists: https://en.wikipedia.org/wiki/List_of_feminists
 //https://en.wikipedia.org/wiki/List_of_female_Nobel_laureates
 //https://en.wikipedia.org/wiki/Women_artists#20th_century
 //http://www.thebookescape.com/Feminista.html


 var feminists= [
    "Marie+Curie", "Frida+Kahlo", "Nina+Simone", "Simone+de+Beauvoir", "Zadie+Smith", "Amelia+Earhart","Aretha+Franklin", 
    "Edith+Wharton", "Baroness+Bertha+Sophie+Felicita+von+Suttner","Maya+Angelou","Alicia+Moreau+de+Justo",'Anaïs+Nin','Helen+of+Anjou',
'Bettisia+Gozzadini',
'Nicola+de+la+Haye',
'Jefimija',
'Christine+de+Pizan',
'Jadwiga+of+Poland',
'Milica+of+Serbia',
'Balaram+Das',
'Laura+Cereta',
'La+Malinche',
'Marie+Dentière', 
'Jane+Anger',
'Marie+de+Gournay',
'Izumo+no+Okuni',
'Modesta+di+Pozzo+di+Forzi',
'Lucrezia+Marinella', 
'Aphra+Behn',
'Anne+Bradstreet',
'Sophia+Elisabet+Brenner',
'Sr.+Sor+Juana+Inés+de+la+Cruz',
'François+Poullain+de+la+Barre',
'Mary+Astell',
'Abigail+Adams',
'Catharina+Ahlgren',
'Annestine+Beyer',
'Eleanor+Butler',
'Marquis+de+Condorcet',
'Anne-Josèphe+Théroigne+de+Méricourt',
'Dorothea+Erxleben',
'Charles+Fourier',
'Jane+Gomeldon',
'Olympe+de+Gouges',
'Sarah+Moore+Grimké',
'Francis+Hutcheson',
'Christian+Isobel+Johnstone',
'Anne+Knight',
'Anna+Maria+Lenngren',
'Francisco+de+Miranda,+Gen.',
'Lucretia+Mott',
'Sarah+Ponsonby',
'Madeleine+de+Puisieux',
'Mary+Shelley',
'Thomas+Thorild',
'Sojourner+Truth',
'Anna+Wheeler',
'Mary+Wollstonecraft',
'Frances+Wright',
'Juliette+Adam',
'Jane+Addams',
'Gertrud+Adelborg',
'Sophie+Adlersparre',
'Alfhild+Agrell',
'Soteria+Aliberty',
'Jules+Allix',
'Elisabeth+Altmann-Gottheiner',
'Qasim+Amin',
'Ellen+Anckarsvärd',
'Adelaide+Anderson',
'Elizabeth+Garrett+Anderson',
'Louisa+Garrett+Anderson',
'Maybanke+Anderson',
'Lovisa+Årberg',
'Edith+Archibald',
'Concepción+Arenal',
'Princess+Louise,+Duchess+of+Argyll',
'Ottilie+Assing',
'Bibi+Khanoom+Astarabadi',
'Louise+Aston',
'Hubertine+Auclert',
'Olympe+Audouard',
'Alice+Constance+Austin',
'Rachel+Foster+Avery',
'Bella+Abzug',
'Ángela+Acuña+Braun',
'Wim+Hora+Adema',
'Dolores+Alexander',
'Maya+Angelou',
'Margery+Corbett+Ashby',
'Ksenija+Atanasijević',
'Ti-Grace+Atkinson',
'Margaret+Atwood',
'Helene+Aylon',
'Eva+Bacon',
'Faith+Bandler',
'Lois+W.+Banner',
'Thelma+Bate',
'Mary+Ritter+Beard',
'Joan+Beauchamp',
'Kay+Beauchamp',
'Simone+de+Beauvoir',
'Helen+Bentwich',
'Rosa+May+Billinghurst',
'Teresa+Billington-Greig',
'Elsie+Bowerman',
'Helen+Gurley+Brown',
'Stella+Browne',
'Susan+Brownmiller',
'Lucy+Burns',
'Karlyn+Kohrs+Campbell',
'Clara+Campoamor',
'Luisa+Capetillo',
'Liz+Carpenter',
'Elvia+Carrillo+Puerto',
'Thérèse+Casgrain',
'Jacqueline+Ceballos',
'Enid+Charles',
'Shirley+St+Hill+Chisholm',
'Hélène+Cixous',
'Eva+Cox',
'Jill+Craigie',
'Minnie+Fisher+Cunningham',
'Hamid+Dalwai',
'Mary+Daly',
'Sonja+Davies',
'Barbara+Deming',
'Ezlynn+Deraniyagala',
'Jeanne+Deroin',
'Jeanne+Deroin',
'Betty+Dodson',
'Sediqeh+Dowlatabadi',
'Carol+Downer',
'Frances+Farrer',
'Geraldine+Ferraro',
'Ana+Figuero',
'Elizabeth+Gurley+Flynn',
'Elizabeth+"Betty"+Bloomer+Ford',
'Gerald+Ford',
'Miles+Franklin',
'Clara+Fraser',
'Elisabeth+Freeman',
'Marilyn+French',
'Betty+Friedan',
'William+Lloyd+Garrison',
'Carol+Gilligan',
'Françoise+Giroud',
'Judy+Goldsmith',
'Jane+Goodall',
'Vivian+Gornick',
'Lois+Gould',
'Jane+Grant',
'Germaine+Greer',
'Colette+Guillaumin',
'Tahar+Haddad',
'Lizzy+Lind+af+Hageby',
'Charlotte+Haldane',
'Gisèle+Halimi',
'Zaib-un-Nissa+Hamidullah',
'Bertha+Harris',
'Caroline+Haslett',
'Dorothy+Hewett',
'Nicole+Hollander',
'Pak+Hon-yong',
'Mary+Howell',
'Edith+How-Martyn',
'Fatima+Ahmed+Ibrahim',
'Fusae+Ichikawa',
'Luce+Irigaray',
'Sonia+Johnson',
'Jill+Johnston',
'Claudia+Jones',
'Rosalie+Gardiner+Jones',
'Marie+Juchacz',
'Alicia+Moreau+de+Justo',
'Raden+Adjeng+Kartini',
'Shidzue+Katō',
'Aoua+Kéita',
'Florynce+Kennedy',
'Annie+Kenney',
'Yamakawa+Kikue',
'Coretta+Scott+King',
'Gerda+Lerner',
'Audre+Lorde',
'Mina+Loy',
'Rae+Luckock',
'Agnes+Macphail',
'Dora+Marsden',
'Elizabeth+Holloway+Marston',
'William+Moulton+Marston',
'Else+Mayer',
'Carolyn+Merchant',
'Maria+Mies',
'Inez+Milholland',
'Kate+Millett',
'Laure+Moghaizel',
'Florence+Nagle',
'Diane+Nash',
'Malak+Hifni+Nasif',
'Anaïs+Nin',
'Helena+Normanton',
'Alexis+Nour',
'Yoko+Ono',
'Alicia+Ostriker',
'Grace+Paley',
'Adela+Pankhurst',
'Christabel+Pankhurst',
'Sylvia+Pankhurst',
'Frances+Parker',
'Alice+Paul',
'Eva+Perón',
'Frédérique+Petrides',
'Marion+Phillips',
'Sylvia+Plath',
'Letty+Cottin+Pogrebin',
'Eileen+Powell',
'Millicent+Preston-Stanley',
'Lorine+Livington+Pruette',
'Funmilayo+Ransome-Kuti',
'Claire+Rayner',
'Adrienne+Rich',
'Mary+Richardson',
'Léa+Roback',
'Hilary+Rose',
'Agnes+Maude+Royden',
'Joanna+Russ',
'Diana+E.+H.+Russell',
'Dora+Russell',
'Manuel+Sacristán',
'Nawal+el-Sadaawi',
'Idola+Saint-Jean',
'Celia+Sánchez',
'George+Sand',
'Flora+Sandes',
'Margaret+Sanger',
'Milunka+Savić',
'Barbara+Seaman',
'Baroness+Seear',
'Huda+Shaarawi',
'Alix+Kates+Shulman',
'Ruth+Simpson',
'Monica+Sjöö',
'Eleanor+Smeal',
'Valerie+Solanas',
'Jo+Spence',
'Gloria+Steinem',
'Doris+Stevens',
'Marie+Stopes',
'Mary+Stott',
'Jessie+Street',
'Edith+Summerskill,+Baroness+Summerskill',
'Elisabeth+Tamm',
'Joan+Kennedy+Taylor',
'Renee+Taylor',
'Tcheng+Yu-hsiu',
'Rini+Templeton',
'Dorothy+Thompson',
'Winifred+Todhunter',
'Jill+Tweedie',
'Mabel+Vernon',
'Harriet+Shaw+Weaver',
'Nesta+Helen+Webster',
'Louise+Weiss',
'Trude+Weiss-Rosmarin',
'Clara+Wichmann',
'Audrey+Wise',
'Monique+Wittig',
'Nellie+Wong',
'Virginia+Woolf',
'Molly+Yard',
'Rosalyn+Baxandall',
'Val+Plumwood',
'Maria+Svolou',
'Lesley+Abdela',
'Carol+J.+Adams',
'Leila+Ahmed',
'Widad+Akrawi',
'Linda+Martín+Alcoff',
'Ayaan+Hirsi+Ali',
'Pam+Allen',
'Isabel+Allende',
'Jane+Alpert',
'Tori+Amos',
'Gloria+E.+Anzaldúa',
'Maria+Arbatova',
'Parvin+Ardalan',
'Élisabeth+Badinter',
'Judi+Bari',
'Kathleen+Barry',
'Benedetta+Barzini',
'Jennifer+Baumgardner',
'Alison+Bechdel',
'Melissa+Benn',
'Lorraine+Bethel',
'Lauran+Bethell',
'Julie+Bindel',
'Sandra+Bloodworth',
'Rosie+Boycott',
'Dionne+Brand',
'Giannina+Braschi',
'Johanna+Brenner',
'Susie+Bright',
'Flora+Brovina',
'Rita+Mae+Brown',
'Carrie+Brownstein',
'Tammy+Bruce',
'Charlotte+Bunch',
'Louise+Burfitt-Dons',
'Judith+Butler',
'Lydia+Cacho',
'Beatrix+Campbell',
'Angela+Carter',
'Ana+Castillo',
'Phyllis+Chesler',
'Margaret+Cho',
'Nancy+Chodorow',
'D.+A.+Clarke',
'Mary+Clark-Glass',
'Hillary+Clinton',
'Carol+Cohn',
'Susan+G.+Cole',
'Patricia+Hill+Collins',
'Sandra+Coney',
'Noreen+Connell',
'Rosalind+Coward',
'Bernadette+Cozart',
'Nikki+Craft',
'Jean+Curthoys',
'Kimberly+Dark',
'Françoise+David',
'Angela+Davis',
'Martha+Davis',
'Christine+Delphy',
'Julie+Delpy',
'Mark+Dery',
'Ani+DiFranco',
'Gail+Dines',
'Fatou+Diome',
'Unity+Dow',
'Donna+Dresch',
'Carol+Ann+Duffy',
'Stephen+Durham',
'Andrea+Dworkin',
'Shirin+Ebadi',
'Barbara+Ehrenreich',
'Gunilla+Ekberg',
'Engy+Ghozlan',
'Bracha+L.+Ettinger',
'Susan+Faludi',
'Fadia+Faqir',
'Melissa+Farley',
'Johanna+Fateman',
'Mary+Flanagan',
'Jo+Freeman,+Joreen',
'Juliette+Fretté',
'Marilyn+Frye',
'Lindsey+German',
'Tavi+Gevinson',
'Lois+Marie+Gibbs',
'Stan+Goff',
'Lucy+Goodison',
'Heide+Göttner-Abendroth',
'Susan+Griffin',
'Emily+Haines',
'Daphne+Hampson',
'Carol+Hanisch',
'Kathleen+Hanna',
'Donna+Haraway',
'Nancy+Hartsock',
'Rosemary+Hennessy',
'Shere+Hite',
'Sarah+Hoagland',
'Risa+Hontiveros-Baraquel',
'Gloria+Jean+Watkins',
'Gillian+Howie',
'Donna+M.+Hughes',
'Holly+Hunter',
'Anna+Hutsol',
'Luzviminda+Ilagan',
'Stevi+Jackson',
'Karla+Jay',
'Sheila+Jeffreys',
'Robert+Jensen',
'Joan+Jett',
'Claire+Johnston',
'Miranda+July',
'Mohja+Kahf',
'Sheema+Kalbasi',
'Wendy+Kaminer',
'Marcelle+Karp',
'Jamie+Keiles',
'Lierre+Keith',
'Petra+Kelly',
'Noushin+Ahmadi+Khorasani',
'Jean+Kilbourne',
'Grace+Ji-Sun+Kim',
'Sirje+Kingsepp',
'Barbara+Kingsolver',
'Bonnie+Sherr+Klein',
'Naomi+Klein',
'Anne+Koedt',
'Andrew+Kooman',
'Peggy+Kornegger',
'Elaheh+Koulaei',
'Sunitha+Krishnan',
'Julia+Kristeva',
'Winona+LaDuke',
'Donna+Laframboise',
'Laura+Lederer',
'Dorchen+Leidholdt',
'John+Lennon',
'Ellie+Levenson',
'Ariel+Levy',
'Olga+Lipovskaya',
'Jacqueline+Livingston',
'Linda+Lovelace',
'Wangari+Maathai',
'Catharine+MacKinnon',
'Sara+Maitland',
'Catherine+Malabou',
'Rosie+Malek-Yonan',
'Irshad+Manji',
'Soe+Tjen+Marching',
'Amanda+Marcotte',
'Mirjana+Marković',
'Angela+Mason',
'Liza+Maza',
'Susan+McClary',
'Wendy+McElroy',
'Patricia+McFadden',
'Jamie+McIntosh',
'Angela+McRobbie',
'Page+Mellish',
'Rigoberta+Menchu',
'Juliet+Mitchell',
'Hayao+Miyazaki',
'Tracey+Moberly',
'Maxine+Molyneux',
'Honor+Moore',
'Cherríe+Moraga',
'Caitlin+Moran',
'Robin+Morgan',
'Laura+Mulvey',
'Sally+Rowena+Munt',
'Jenni+Murray',
'Inga+Muscio',
'Kathy+Najimy',
'Suniti+Namjoshi',
'Taslima+Nasrin',
'Benjamin+Nolot',
'Asra+Nomani',
'Martha+Nussbaum',
'Ann+Oakley',
'Sandra+Oh',
'Lars+Ohly',
'Ellen+Page',
'Camille+Paglia',
'Amanda+Palmer',
'Carole+Pateman',
'Nancy+Paterson',
'Vesna+Pešić',
'Irene+Peslikis',
'Liz+Phair',
'Mary+Pipher',
'Katha+Pollitt',
'Griselda+Pollock',
'Soraya+Post',
'Anastasia+Powell',
'Sharon+Presley',
'Jerilynn+Prior',
'Maria+Raha',
'Janice+Raymond',
'Bernice+Johnson+Reagon',
'Helen+Reddy',
'Elizabeth+Anne+Reid',
'Abby+Rockefeller',
'Ninotchka+Rosca',
'Jacqueline+Rose',
'Sheila+Rowbotham',
'Gayle+Rubin',
'Kathy+Rudy',
'Shadi+Sadr',
'Gita+Sahgal',
'Sarojini+Sahoo',
'JD+Samson',
'Michael+Sandel',
'Justin+Sane',
'Thomas+Sankara',
'Kathie+Sarachild',
'Anita+Sarkeesian',
'Marjane+Satrapi',
'Marie-Laure+Sauty+de+Chalon',
'Alice+Schwarzer',
'Gudrun+Schyman',
'Lynne+Segal',
'Shamima+Shaikh',
'Shahla+Sherkat',
'Vandana+Shiva',
'Elaine+Showalter',
'Ann+Simonton',
'Carol+Smart',
'Barbara+Smith',
'Joan+Smith',
'Valerie+Smith',
'Kate+Smurthwaite',
'Cornelia+Sollfrank',
'Patricia+Soltysik',
'Christina+Hoff+Sommers',
'Kate+Soper',
'Donita+Sparks',
'Dale+Spender',
'Charlene+Spretnak',
'Annie+Sprinkle',
'Starhawk',
'Debbie+Stoller',
'John+Stoltenberg',
'Nadine+Strossen',
'Lucy+Suchman',
'Anne+Summers',
'Karlina+Leksono+Supelli',
'Helen+Sworn',
'Kazimiera+Szczuka',
'Lili+Taylor',
'J.+Ann+Tickner',
'Roya+Toloui',
'Corin+Tucker',
'Robin+Tunney',
'Urvashi+Vaid',
'Tobi+Vail',
'Jessica+Valenti',
'Norah+Vincent',
'Kajsa+Wahlberg',
'Hilary+Wainwright',
'Alice+Walker',
'Rebecca+Walker',
'Michele+Wallace',
'Natasha+Walter',
'Peng+Wan-ru',
'Warcry',
'Joss+Whedon',
'Faith+Wilding',
'Ellen+Willis',
'Kaia+Wilson',
'Oprah+Winfrey',
'Valerie+Wise',
'Naomi+Wolf',
'Allison+Wolfe',
'Alice+Wolfson',
'Elizabeth+Wurtzel',
'Cathy+Young',
'Stasa+Zajovic',
'Sande+Zeig',
'Julie+Zeilinger',
'Misako+Enoki',
'Virginia+Vargas',
'Jane+Addams',
'Susan+B.+Anthony',
'Marie+Antoinette',
'Saint+Joan+of+Arc',
'Aspasia+of+Miletus',
'Jane+Austen',
'Ella+Baker',
'Sirimavo+Ratwatte+Dias+Bandaranaike',
'Clara+Barton',
'Florence+Bascom',
'Simone+de+Beauvoir',
'Aphra+Behn',
'Elizabeth+Blackwell',
'Bonnie+Kathleen+Blair',
'Rosa+Bonheur',
'Louise+Arner+Boyd',
'Pearl+S.+Buck',
'Marie+Anne+de+Cupis+de+Camargo',
'Rachel+Carson',
'Catherine+the+Great',
'Chien-shiung+Wu',
'Cleopatra',
'Juana+Ines+de+la+Cruz',
'Marie+Curie',
'Agnes+George+de+Mille',
'Emily+Dickinson',
'Amelia+Earhart',
'Marian+Wright+Edelman',
'Eleanor+of+Aquitane',
'Beatrix+Jones+Farrand',
'Edith+Flanigen',
'Anne+Frank',
'Betty+Naomi+Friedan',
'Margaret+Fuller',
'Indira+Gandhi',
'Sarah+and+Angelina+Grimke',
'Caroline+Lucretia+Herschel',
'Dorothy+Mary+Crowfoot+Hodgkin',
'Ariel+Hollinshead',
'Mary+Phelps+Jacob',
'Helen+Keller',
'Billie+Jean+King',
'Elizabeth+Kubler-Ross',
'Maya+Lin',
'Juliette+Gordon+Low',
'Anne+Sullivan+Macy',
'Wilma+Mankiller',
'Barbara+McClintock',
'Catherine+de+Medici',
'Lise+Meitner',
'Rigoberta+Menchu+Tum',
'Maria+Montessori',
'Mother+Theresa',
'Florence+Nightingale',
"Georgia+O'Keeffe",
'Vijaya+Lakshimi+Pandit',
'Emmeline+Pankhurst',
'Rosa+Parks',
'Eva+Peron',
'Christine+de+Pizan',
'Pocahontas',
'Queen+Elizabeth+I',
'Queen+Isabella',
'Queen+Victoria',
'Jeannette+Rankin',
'Sally+Ride',
'Alexandra+Romanov',
'Eleanor+Roosevelt',
'Sakajawea',
'Margaret+Sanger',
'Sappho',
'Rose+Schneiderman',
'Gloria+Steinem',
'Lucy+Stone',
'Harriet+Beecher+Stowe',
'Harriet+Russell+Strong',
'Bertha+von+Suttner',
'Emma+Tenayuca',
'Valentina+Vladimirovna+Nikolayeva+Tereshkova',
'Margaret+Thatcher',
'Alexandrine+Pieternella+Francoise+Tinne',
'Sojourner+Truth',
'Harriet+Tubman',
"Tz'u+Hsi",
'Yoshiko+Uchida',
'Mary+Wollstonecraft',
'Rosalyn+Sussman+Yalow',
'Jane+Addams',
'Svetlana+Alexievich',
'Emily+Greene+Balch',
'Françoise+Barré-Sinoussi',
'Elizabeth+Blackburn',
'Linda+B.+Buck',
'Pearl+S.+Buck',
'Gerty+Theresa+Cori',
'Mairead+Corrigan',,
'Grazia+Deledda',
'Shirin+Ebadi',
'Gertrude+B.+Elion',
'Leymah+Gbowee',
'Maria+Goeppert-Mayer',
'Nadine+Gordimer',
'Carol+W.+Greider',
'Dorothy+Crowfoot+Hodgkin',
'Elfriede+Jelinek',
'Ellen+Johnson+Sirleaf',
'Irène+Joliot-Curie',
'Tawakel+Karman',
'Selma+Lagerlöf',
'Doris+Lessing',
'Rita+Levi-Montalcini',
'Wangari+Maathai',
'Barbara+McClintock',
'Rigoberta+Menchú',
'Gabriela+Mistral',
'Toni+Morrison',
'May-Britt+Moser',
'Herta+Müller',
'Alice+Munro',
'Alva+Myrdal',
'(shared+with+Alfonso+García+Robles)',
'Christiane+Nüsslein-Volhard',
'Elinor+Ostrom',
'Nelly+Sachs',
'Bertha+von+Suttner',
'Aung+San+Suu+Kyi',
'Wisława+Szymborska',
'Mother+Teresa',
'Sigrid+Undset',
'Betty+Williams',
'Jody+Williams',
'Ada+E.+Yonath',
'Malala+Yousafzai',
'Tu+Youyou',
'Hypatia',
'Aedesia+of+Alexandria',
"Tullia+d'Aragona",
'Catherine+of+Siena',
'Moderata+Fonte',
'Hildegard+of+Bingen',
'Hannah+Arendt',
'Mary+Astell',
'Laura+Bassi',
'Antoinette+Brown+Blackwell',
'Mary+Whiton+Calkins',
'Émilie+du+Châtelet',
'Catharine+Trotter+Cockburn',
'Anne+Conway',
'Helene+von+Druskowitz',
'George+Eliot',
'Hannelore+Baron',
'Lee+Bontecou',
'Louise+Bourgeois',
'Romaine+Brooks',
'Emily+Carr',
'Leonora+Carrington',
'Mary+Cassatt',
'Elizabeth+Catlett',
'Camille+Claudel',
'Sonia+Delaunay',
'Dulah+Marie+Evans',
'Audrey+Flack',
'Mary+Frank',
'Helen+Frankenthaler',
'Elisabeth+Frink',
'Wilhelmina+Weber+Furlong',
'Françoise+Gilot',
'Natalia+Goncharova',
'Nancy+Graves',
'Grace+Hartigan',
'Barbara+Hepworth',
'Eva+Hesse',
'Sigrid+Hjertén',
'Hannah+Höch',
'Frances+Hodgkins',
'Malvina+Hoffman',
'Margaret+Ponce+Israel',
'Gwen+John',
'Käthe+Kollwitz',
'Lee+Krasner',
'Frida+Kahlo',
'Laura+Knight',
'Barbara+Kruger',
'Marie+Laurencin',
'Tamara+de+Lempicka',
'Séraphine+Louis',
'Dora+Maar',
'Margaret+Macdonald+Mackintosh',
'Maruja+Mallo',
'Agnes+Martin',
'Ana+Mendieta',
'Joan+Mitchell',
'Paula+Modersohn-Becker',
'Gabriele+MünterAlice+Neel',
'Louise+Nevelson',
"Georgia+O'Keeffe",
'Orovida+Camille+Pissarro',
'Irene+Rice+Pereira',
'Bridget+Riley',
'Verónica+Ruiz+de+Velasco',
'Anne+Ryan',
'Charlotte+Salomon',
'Augusta+Savage',
'Zofia+Stryjeńska',
'Zinaida+Serebriakova',
'Sarai+Sherman',
'Henrietta+Shore',
'Sr.+Maria+Stanisia',
'Marjorie+Strider',
'Suzanne+Valadon',
'Remedios+Varo',
'Maria+Helena+Vieira+da+Silva',
'Nellie+Walker',
'Marianne+von+Werefkin',
'Ogura+Yuki',
'Dorothy+Allison',
'Maya+Angelou',
'Margaret+Atwood',
'Beryl+Bainbridge',
'Toni+Cade+Bambara',
'Djuna+Barnes',
'Pat+Barker',
'Anita+Brookner',
'Rita+Mae+Brown',
'Pearl+S.+Buck',
'A.+S.+Byatt',
'Angela+Carter',
'Ana+Castillo',
'Willa+Cather',
'Kate+Chopin',
'Sandra+Cisneros',
'Ivy+Compton-Burnett',
'Anita+Desai',
'Isak+Dinesen',
'Harriet+Doerr',
'Margaret+Drabble',
'Dumaurier',
'Buchi+Emecheta',
'Louise+Erdrich',
'Penelope+Fitzgerald',
'Fannie+Flagg',
'Janet+Frame',
'Marilyn+French',
'Rebecca+Goldstein',
'Nadine+Gordimer',
'Mary+Gordon',
'Radclyffe+Hall',
'Bessie+Head',
'Patricia+Highsmith',
'Janet+Hobhouse',
'Keri+Hulme',
'Zora+Neal+Hurston',
'Shirley+Jackson',
'Ruth+Prawer+Jhabvala',
'Erica+Jong',
'Jamaica+Kincaid',
'Barbara+Kingsolver',
'Maxine+Hong+Kingston',
'Joy+Kogawa',
'Margaret+Laurence',
'Harper+Lee',
'Doris+M.+Lessing',
'Penelope+Lively',
'Anita+Loos',
'Olivia+Manning',
'Mary+McCarthy',
'Carson+McCullers',
'Terry+McMillan',
'Isabel+Miller',
'Margaret+Mitchell',
'Lorrie+Moore',
'Toni+Morrison',
'Bharati+Mukherjee',
'Alice+Munro',
'Iris+Murdoch',
"Edna+O'Brien",
"Flannery+O'Connor",
'Tillie+Olsen',
'Grace+Paley',
'Dorothy+Parker',
'Jayne+Anne+Phillips',
'Marge+Piercy',
'Sylvia+Plath',
'Katherine+Anne+Porter',
'Dawn+Powell',
'E.+Annie+Proulx',
'Ayn+Rand',
'Mary+Renault',
'Jean+Rhys',
'Marilynn+Robinson',
'Arundati+Roy',
'May+Sarton',
'Carol+Shields',
'Anita+Shreve',
'Mona+Simpson',
'Elizabeth+Smart',
'Jane+Smiley',
'Susan+Sontag',
'Muriel+Spark',
'Elizabeth+Taylor',
'Amy+Tan',
'Anne+Tyler',
'Jane+Urquhart',
'Alice+Walker',
'Fay+Weldon',
'Eudora+Welty',
'Rebecca+West',
'Edith+Wharton',
'Antonia+White',
'Jeanette+Winterson',
'Virginia+Woolf',
'Jane+Austen',





































































































































  ];